export enum WaitingRoomEvents {
    IsGameCreator = 'isGameCreator',
    IsRoomFull = 'isRoomFull',
    JoinGameRoom = 'joinGameRoom',
    LeaveGameRoom = 'leaveGameRoom',
    LeaveQueueRoom = 'leaveQueueRoom',
    CreatorLeftGame = 'creatorLeftGame',
    OpponentLeftGame = 'opponentLeftGame',
    OpponentJoinedGame = 'opponentJoinedGame',
    GetGameRooms = 'getGameRooms',
    ResponseOfCreator = 'responseOfCreator',
    CreatorUsername = 'creatorUsername',
    GiveCreatorUsername = 'giveCreatorUsername',
    GetCreatorUsername = 'getCreatorUsername',
    DeleteGame = 'deleteGame',
}
